services:
  - type: web
    name: active-dev-badge
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
